# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Victor Holanda
email: jvictor_holanda@outlook.com
copyright_name: "Victor Holanda"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://victorholanda21.github.io/"

description: >- # this means to ignore newlines until "baseurl:"
  Amante de tecnologia, gestão e projetos. Com dedicação, sigo em busca de alcançar todos os meus objetivos pessoais, acadêmicos e profissionais.

github_username: VictorHolanda21
facebook_username: victorholanda21
linkedin_username: victorholanda21
email_username: jvictor_holanda@outlook.com

avatar: https://avatars3.githubusercontent.com/u/12675056?s=400&u=75e88e527d6365ce28f32f239e4ef9ee8ae88190&v=4

timezone: America/Fortaleza

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
